### ISSUE TITLE
Brick landing page : hero-section

### ISSUE THREAD

**Issue by zeerau** [Ingressive-for-Good/Devas#15]
implementing the hero section @Ingressive-for-Good/devas 
![repohero](https://user-images.githubusercontent.com/81034521/136839414-c0449b7e-aa9a-4829-9590-4eeee1c5a012.jpeg)

**Comment by itsPrajapat** [comment]
Could You Please assign this issue to me

**Comment by sarthakahuja07** [comment]
Hi!! Can you assign this to me, I would love to work on this
