### ISSUE TITLE
Brick landing page : footer

### ISSUE THREAD

**Issue by zeerau** [Ingressive-for-Good/Devas#19]
implementing the footer the section @Ingressive-for-Good/devas 
![repofooter](https://user-images.githubusercontent.com/81034521/136839813-04ca4e6f-0123-451d-9cdc-b8af63cc814a.jpeg)

**Comment by itsPrajapat** [comment]
I want to work on this. Could You please assign this issue to me

**Comment by sarthakahuja07** [comment]
Hi!! Can you assign this to me, I would love to work on this
